        IFNDEF MCB152_INC
MCB152_INC      EQU     1
;**
;**     $Filename: mcb152.inc
;**     $Release: 1
;**     $Revision: 0
;**     $Date: 09/08/1998
;**
;**     MCB152 complete system include
;**
;**     Coded by Joachim Elen
;**

        INCLUDE "ascii.inc"
        INCLUDE "hardware.inc"
        INCLUDE "kick.inc"
        INCLUDE "library.inc"
        INCLUDE "macros.inc"
        

        ENDIF   ; MCB152_INC
